version: '3.8'

services:
  gpu-monitor:
    build: .
    ports:
      - "5050:5050"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
